dist: bionic
sudo: false
language: python
# Working towards support https://numpy.org/neps/nep-0029-deprecation_policy.html
python:
  - "3.8"
env: #split tests
  global:
    - REQUIRES_PYNBODY=false
    - REQUIRES_ASTROPY=false
    - REQUIRES_ASTROQUERY=false
    - PYTHON_COVREPORTS_VERSION=3.8 # Version for which reports are uploaded
  matrix:
    - TEST_FILES='tests/ --ignore=tests/test_qdf.py --ignore=tests/test_pv2qdf.py --ignore=tests/test_diskdf.py --ignore=tests/test_orbit.py --ignore=tests/test_streamdf.py --ignore=tests/test_streamgapdf.py --ignore=tests/test_evolveddiskdf.py --ignore=tests/test_quantity.py --ignore=tests/test_nemo.py --ignore=tests/test_amuse.py --ignore=tests/test_coords.py --ignore=tests/test_jeans.py --ignore=tests/test_orbits.py --ignore=tests/test_dynamfric.py' REQUIRES_PYNBODY=true
    - TEST_FILES='tests/test_quantity.py tests/test_coords.py' REQUIRES_ASTROPY=true # needs to be separate for different config
    - TEST_FILES='tests/test_orbit.py tests/test_orbits.py' REQUIRES_PYNBODY=true REQUIRES_ASTROPY=true REQUIRES_ASTROQUERY=true
    - TEST_FILES='tests/test_evolveddiskdf.py tests/test_jeans.py tests/test_dynamfric.py'
    - TEST_FILES='tests/test_qdf.py tests/test_pv2qdf.py tests/test_streamgapdf.py'
    - TEST_FILES='tests/test_diskdf.py'
    - TEST_FILES='tests/test_streamdf.py'
matrix: # only run crucial tests for python 2.7, 3.6, 3.7
  include:
    - python: "2.7"
      env: TEST_FILES='tests/test_orbit.py tests/test_orbits.py' REQUIRES_PYNBODY=true REQUIRES_ASTROPY=true REQUIRES_ASTROQUERY=true
    - python: "3.6"
      env: TEST_FILES='tests/test_orbit.py tests/test_orbits.py' REQUIRES_PYNBODY=true REQUIRES_ASTROPY=true REQUIRES_ASTROQUERY=true
    - python: "3.7"
      env: TEST_FILES='tests/test_orbit.py tests/test_orbits.py' REQUIRES_PYNBODY=true REQUIRES_ASTROPY=true REQUIRES_ASTROQUERY=true
addons:
  apt:
    packages:
     - libgsl0-dev
#    - lcov # leave for when they approve its use
services:
  - xvfb
before_install:
 # skip travis build if [skip travis] or [travis skip] in commit message
 - if git show -s HEAD | grep -F -q "[skip travis]" ; then echo "skip travis" && exit 0 ; fi
 - if git show -s HEAD | grep -F -q "[travis skip]" ; then echo "skip travis" && exit 0 ; fi
 # Install lcov
 - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
 - tar xf lcov_1.11.orig.tar.gz
 - mkdir $HOME/usr
 - export PATH=$HOME/usr/bin:$PATH
 - make -C lcov-1.11/ install PREFIX=$HOME
 #Setup conda for faster installs
 - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
 - bash miniconda.sh -b -p $HOME/miniconda
 - export PATH="$HOME/miniconda/bin:$PATH"
 - hash -r
 - conda config --set always_yes yes --set changeps1 no
 - conda update conda
 - conda config --add channels conda-forge
# Make defaults again the highest priority channel
 - conda config --add channels defaults
# setuptools >= 45 no longer supports Python 2
 - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then SETUPTOOLS_VERSION="<45"; else SETUPTOOLS_VERSION=""; fi
 - conda create -n test-environment python=$TRAVIS_PYTHON_VERSION "numpy>=1.16" scipy matplotlib numexpr "setuptools$SETUPTOOLS_VERSION" pip "cython>=0.20" pytest
 - source activate test-environment
#Download corrections for some tests
 - curl -O https://github.s3.amazonaws.com/downloads/jobovy/galpy/galpy-dfcorrections.tar.gz
 - tar xvzf galpy-dfcorrections.tar.gz -C ./galpy/df/data/
# command to install dependencies
install:
 - if [[ $TRAVIS_PYTHON_VERSION == $PYTHON_COVREPORTS_VERSION ]]; then conda install gsl; fi
 - pip install 'coverage==4.1' --force-reinstall # necessary bc of backward incompatible change in 4.2 about combining reports
 - pip install pytest-cov
 - if [[ $TRAVIS_PYTHON_VERSION == $PYTHON_COVREPORTS_VERSION ]]; then pip install coveralls-merge; fi
 - if [[ $TRAVIS_PYTHON_VERSION == $PYTHON_COVREPORTS_VERSION ]]; then gem install coveralls-lcov; fi
 - if [[ $TRAVIS_PYTHON_VERSION == $PYTHON_COVREPORTS_VERSION ]]; then easy_install --upgrade requests; fi
 - if [[ $TRAVIS_PYTHON_VERSION == $PYTHON_COVREPORTS_VERSION ]]; then easy_install --upgrade coveralls; fi
# pynbody, install deps with conda as much as possible
 - if $REQUIRES_PYNBODY; then conda install h5py pandas pytz; fi
 - if $REQUIRES_PYNBODY && [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then pip install pynbody==0.48; fi
 - if $REQUIRES_PYNBODY && [[ $TRAVIS_PYTHON_VERSION != 2.7 ]]; then pip install git+git://github.com/pynbody/pynbody.git; fi
 # clone my version of the torus code, don't do this for one test, to make sure the code installs without the torus code
 - if [[ $TEST_FILES != 'tests/test_evolveddiskdf.py tests/test_jeans.py' ]]; then git clone https://github.com/jobovy/Torus.git galpy/actionAngle/actionAngleTorus_c_ext/torus; fi
 - if [[ $TEST_FILES != 'tests/test_evolveddiskdf.py tests/test_jeans.py' ]]; then cd galpy/actionAngle/actionAngleTorus_c_ext/torus; fi
 - if [[ $TEST_FILES != 'tests/test_evolveddiskdf.py tests/test_jeans.py' ]]; then git checkout galpy; fi
 - if [[ $TEST_FILES != 'tests/test_evolveddiskdf.py tests/test_jeans.py' ]]; then cd -; fi
 - if $REQUIRES_ASTROPY && [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then conda install astropy --no-deps; fi
 - if $REQUIRES_ASTROPY && [[ $TRAVIS_PYTHON_VERSION != 2.7 ]]; then pip install astropy==4.1rc2 --no-deps; fi
 - if $REQUIRES_ASTROQUERY && [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then pip install astroquery==0.4; fi
 - if $REQUIRES_ASTROQUERY && [[ $TRAVIS_PYTHON_VERSION != 2.7 ]]; then pip install astroquery; fi
 - if $REQUIRES_ASTROQUERY && [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then pip install "pytest>=4.6.2"; fi
# Compile w/o OpenMP for one, to make sure that works
 - if [[ $TRAVIS_PYTHON_VERSION != $PYTHON_COVREPORTS_VERSION ]] && [[ $TEST_FILES == 'tests/test_evolveddiskdf.py tests/test_jeans.py' ]]; then python setup.py build_ext --coverage --single_ext --inplace --no-openmp; else python setup.py build_ext --coverage --single_ext --inplace; fi
 - python setup.py develop --single_ext
# Following tests that we can start from an incomplete configuration file
 - if [[ $TEST_FILES == 'tests/test_evolveddiskdf.py tests/test_jeans.py' ]]; then echo -e '[normalization]' > $HOME/.galpyrc && echo -e 'ro = 8.' >> $HOME/.galpyrc && echo -e 'vo = 220.' >> $HOME/.galpyrc; fi
 - if [[ $TEST_FILES == 'tests/test_diskdf.py' ]]; then echo -e '[normalization]' > $HOME/.galpyrc && echo -e 'ro = 8.' >> $HOME/.galpyrc && echo -e '[astropy]' >> $HOME/.galpyrc && echo -e 'astropy-units = False' >> $HOME/.galpyrc && echo -e '[plot]' >> $HOME/.galpyrc && echo -e 'seaborn-bovy-defaults = True' >> $HOME/.galpyrc && echo -e '[warnings]' >> $HOME/.galpyrc && echo -e 'verbose = True' >> $HOME/.galpyrc; fi
# Print versions of everything relevant
 - python -c "import numpy; print(numpy.__version__)"
 - python -c "import scipy; print(scipy.__version__)"
 - python -c "import matplotlib; print(matplotlib.__version__)"
 - if $REQUIRES_ASTROPY; then python -c "import astropy; print(astropy.__version__)"; fi
 - if $REQUIRES_ASTROQUERY; then python -c "import astroquery; print(astroquery.__version__)"; fi
 - if $REQUIRES_PYNBODY; then python -c "import pynbody; print(pynbody.__version__)"; fi
# RUN TESTS
script:
# only wait longer for orbit integrations
 - if [[ $TEST_FILES == 'tests/test_orbit.py tests/test_orbits.py' ]]; then travis_wait 40 pytest -v $TEST_FILES --cov galpy --cov-config .coveragerc_travis --disable-pytest-warnings; else pytest -v $TEST_FILES --cov galpy --cov-config .coveragerc_travis --disable-pytest-warnings; fi
after_success:
 # Generate lcov output 
 - if [[ $TRAVIS_PYTHON_VERSION == $PYTHON_COVREPORTS_VERSION ]]; then lcov --capture --base-directory . --directory build/temp.linux-x86_64-$PYTHON_COVREPORTS_VERSION/galpy/ --no-external --output-file coverage_full.info; fi
 - if [[ $TRAVIS_PYTHON_VERSION == $PYTHON_COVREPORTS_VERSION ]]; then lcov --remove coverage_full.info 'galpy/actionAngle/actionAngleTorus_c_ext/torus/*' -o coverage.info; fi
 # Codecov, need to edit bash uploader for incorrect TRAVIS_PYTHON_VERSION environment variable matching, at least until codecov/codecov-bash#133 is resolved
 - curl -s https://codecov.io/bash > .codecov
 - sed -i -e 's/TRAVIS_.*_VERSION/^TRAVIS_.*_VERSION=/' .codecov
 - chmod +x .codecov
# - if [[ $TRAVIS_PYTHON_VERSION == $PYTHON_COVREPORTS_VERSION ]]; then bash <(curl -s https://codecov.io/bash) -X gcov; fi
 - if [[ $TRAVIS_PYTHON_VERSION == $PYTHON_COVREPORTS_VERSION ]]; then ./.codecov -X gcov; fi
 # coveralls: combine, generate json, and upload
 - if [[ $TRAVIS_PYTHON_VERSION == $PYTHON_COVREPORTS_VERSION ]]; then coveralls-lcov -v -n coverage.info > coverage.c.json; fi
 - if [[ $TRAVIS_PYTHON_VERSION == $PYTHON_COVREPORTS_VERSION ]]; then coveralls-merge coverage.c.json; fi
notifications:
  email:
    recipients:
      - jo.bovy@gmail.com
    on_success: change
    on_failure: change
